In [1]:
import numpy as np
import torch

In [51]:
X = np.arange(4*4).reshape(4,1,2,2) # (samples, layers, rows, cols)
print(X.shape)
print(X)
print(X[0,0,0,0])
print(X[1,0,0,1])
print(X[2,0,1,0])
print(X[3,0,1,1])

(4, 1, 2, 2)
[[[[ 0  1]
   [ 2  3]]]


 [[[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]]]
0
5
10
15


In [54]:
idxs = np.array([1,0])#.reshape(1,1,2)
#print(idxs)

idxs = np.array([[1,0],[0,0]])#.reshape(1,1,2)
#print(idxs)
#print(idxs.shape)

idxs = np.array([
#    [(0,0),(1,1)],
#    (0,1),
#    (1,0),
#    (1,1)
    [[0,0],[1,1]],
    [0,1],
    [1,0],
    [1,1]
])
print(idxs)
print(idxs.shape)

[[list([0, 0]) list([1, 1])]
 [0 1]
 [1 0]
 [1 1]]
(4, 2)


In [65]:
tows = [x[0][tuple(idx)] for x,idx in zip(X,idxs)]
print(tows)
tows = np.array(tows).flatten()
print(tows)

[array([1, 1]), 5, 10, 15]
[array([1, 1]) 5 10 15]


In [57]:
idxs_dict = {i:np.array(c) for i,c in enumerate(idxs)}
idxs_dict

{0: array([list([0, 0]), list([1, 1])], dtype=object),
 1: array([0, 1], dtype=object),
 2: array([1, 0], dtype=object),
 3: array([1, 1], dtype=object)}

In [58]:
#tows = [x[0][idxs_dict[i]] for i,x in enumerate(X)]
tows = [idxs_dict[i] for i,x in enumerate(X)]
tows

[array([list([0, 0]), list([1, 1])], dtype=object),
 array([0, 1], dtype=object),
 array([1, 0], dtype=object),
 array([1, 1], dtype=object)]

In [62]:
X_t = torch.Tensor(X)
print(X_t.size())
idxs_t = torch.Tensor(idxs)

torch.Size([4, 1, 2, 2])


TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.